/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Point = t.iface([], {
  "x": "number",
  "y": "number",
});

export const NewArea = t.iface([], {
  "origin": "Point",
  "width": "number",
  "height": "number",
});

export const TaggedArea = t.iface(["NewArea"], {
  "title": "string",
});

export const ImageDimensions = t.iface([], {
  "width": "number",
  "height": "number",
});

export const EditAreaPayload = t.iface([], {
  "index": "number",
  "movX": "number",
  "movY": "number",
});

export const EditTitlePayload = t.iface([], {
  "index": "number",
  "title": "string",
});

export const TaggedImageData = t.iface([], {
  "imageData": t.union("string", "undefined"),
  "imageDimensions": t.union("ImageDimensions", "undefined"),
  "taggedAreas": t.array("TaggedArea"),
});

export const ImageTaggerState = t.iface(["TaggedImageData"], {
  "selected": t.union("number", "undefined"),
  "error": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Point,
  NewArea,
  TaggedArea,
  ImageDimensions,
  EditAreaPayload,
  EditTitlePayload,
  TaggedImageData,
  ImageTaggerState,
};
export default exportedTypeSuite;
